Fix double path before ::PYLINT
carsongee/pytest-pylint pull request #140
Opened 2020-07-30 15:17 UTC by yanqd0

## 2

There are double paths before `::PYLINT` in `pytest --verbose` mode. It is fixed in my second commit.

```shell
$ pytest -v -m pylint
=============================== test session starts ===============================
platform linux -- Python 3.7.7, pytest-6.0.0, py-1.9.0, pluggy-0.13.1 -- /home/yanqd0/pytest-pylint/.env/bin/python
cachedir: .pytest_cache
rootdir: /home/yanqd0/pytest-pylint, configfile: tox.ini
plugins: flake8-1.0.6, pylint-0.17.0
collected 38 items / 31 deselected / 7 selected                                   
--------------------------------------------------------------------------------
Linting files
.......
--------------------------------------------------------------------------------

setup.py::/home/yanqd0/pytest-pylint/setup.py::PYLINT PASSED [ 14%]
pytest_pylint/__init__.py::/home/yanqd0/pytest-pylint/pytest_pylint/__init__.py::PYLINT PASSED [ 28%]
pytest_pylint/plugin.py::/home/yanqd0/pytest-pylint/pytest_pylint/plugin.py::PYLINT PASSED [ 42%]
pytest_pylint/pylint_util.py::/home/yanqd0/pytest-pylint/pytest_pylint/pylint_util.py::PYLINT PASSED [ 57%]
pytest_pylint/util.py::/home/yanqd0/pytest-pylint/pytest_pylint/util.py::PYLINT PASSED [ 71%]
pytest_pylint/tests/test_pytest_pylint.py::/home/yanqd0/pytest-pylint/pytest_pylint/tests/test_pytest_pylint.py::PYLINT PASSED [ 85%]
pytest_pylint/tests/test_util.py::/home/yanqd0/pytest-pylint/pytest_pylint/tests/test_util.py::PYLINT PASSED [100%]

======================== 7 passed, 31 deselected in 2.63s =========================
```

## 1

There are 2 kinds of pylint issues, which fail the build.

```shell
$ pytest
=============================== test session starts ===============================
platform linux -- Python 3.7.7, pytest-6.0.0, py-1.9.0, pluggy-0.13.1
rootdir: /home/yanqd0/pytest-pylint, configfile: tox.ini
plugins: flake8-1.0.6, pylint-0.17.0
collected 38 items
--------------------------------------------------------------------------------
Linting files
.......
--------------------------------------------------------------------------------

setup.py ..                                                                 [  5%]
pytest_pylint/__init__.py ..                                                [ 10%]
pytest_pylint/plugin.py F.                                                  [ 15%]
pytest_pylint/pylint_util.py ..                                             [ 21%]
pytest_pylint/util.py ..                                                    [ 26%]
pytest_pylint/tests/test_pytest_pylint.py F......................           [ 86%]
pytest_pylint/tests/test_util.py .....                                      [100%]

==================================== FAILURES =====================================
________________________ [pylint] pytest_pylint/plugin.py _________________________
W:269, 0: Method 'get_closest_marker' is abstract in class 'Node' but is not overridden (abstract-method)
W:269, 0: Method 'gethookproxy' is abstract in class 'FSCollector' but is not overridden (abstract-method)
W:269, 0: Method 'isinitpath' is abstract in class 'FSCollector' but is not overridden (abstract-method)
W:302, 0: Method 'get_closest_marker' is abstract in class 'Node' but is not overridden (abstract-method)
_______________ [pylint] pytest_pylint/tests/test_pytest_pylint.py ________________
E:145, 1: pytest.mark.parametrize is not callable (not-callable)
E:180, 1: pytest.mark.parametrize is not callable (not-callable)
E:284, 1: pytest.mark.parametrize is not callable (not-callable)
E:298, 1: pytest.mark.parametrize is not callable (not-callable)
============================= short test summary info =============================
FAILED pytest_pylint/plugin.py::/home/yanqd0/pytest-pylint/pytest_pylint/plugin.py::PYLINT
FAILED pytest_pylint/tests/test_pytest_pylint.py::/home/yanqd0/pytest-pylint/pytest_pylint/tests/test_pytest_pylint.py::PYLINT
========================== 2 failed, 36 passed in 4.83s ===========================
```
`abstract-method` is because `pytest 0.6.0` sets 3 methods to raise `NotImplementedError`. But they are used only in `_collectfile`, which is called in `Session`. There is no need to implement them in `File` or `Item`.

`not-callable` is more interesting. `pylint` maybe find the wrong way in `pytest 0.6.0`. It should go to [src/_pytest/python.py#L916](https://github.com/pytest-dev/pytest/blob/6.0.0/src/_pytest/python.py#L916), not to [src/_pytest/mark/structures.py#L481](https://github.com/pytest-dev/pytest/blob/6.0.0/src/_pytest/mark/structures.py#L481).

```python
# See TYPE_CHECKING above.
if TYPE_CHECKING:
    # Using casts instead of type comments intentionally - issue #7473.
    # TODO(py36): Change to builtin annotation syntax.
    skip = cast(_SkipMarkDecorator, None)
    skipif = cast(_SkipifMarkDecorator, None)
    xfail = cast(_XfailMarkDecorator, None)
    parametrize = cast(_ParametrizeMarkDecorator, None)
    usefixtures = cast(_UsefixturesMarkDecorator, None)
    filterwarnings = cast(_FilterwarningsMarkDecorator, None)
```

So, they are disabled in my first commit.

2020-10-12 09:27 UTC, R-Broadley commented
Adding support for this change and highlighting further benefits.

This change will also fix compatibility issues between pytest-pylint and the report plugins pytest-html, allure-pytest when using Windows. 
On Windows, files in a users home directory have an absolute path like `C:\Users\<username>\...` due to the use of `\` and the `U` which follows this causes issues for the above mentioned plugins as `\U` leads to a `UnicodeDecodeError`. See pytest-dev/pytest-html#342 and allure-framework/allure-python#280

This change also brings the output in-line with pytest-black, pytest-pydocstyle, pytest-isort.
With this change the short test summary info for `pytest --pylint --black --isort --pydocstyle` and a setup.py that fails for all is:
```
FAILED setup.py::BLACK
FAILED setup.py::PYLINT
FAILED setup.py::PYDOCSTYLE
FAILED setup.py::ISORT
```
Prior to this change the output was:
```
FAILED setup.py::BLACK
FAILED setup.py::<full path to setup.py>::PYLINT
FAILED setup.py::PYDOCSTYLE
FAILED setup.py::ISORT
```

This change does not fully align with these plugins and this shows in the allure report output when running with `--pylint --black --isort --pydocstyle`. The tree of tests suits in allure for tests of setup.py appears as follows with this change:
```
setup.py
    # setup.py
    # setup.py
    # setup.py
    # PYLINT
```
Arguably showing PYLINT here is the better behaviour, but should you prefer consistency, the following change would further align the reporting:
```python
  def collect(self):
      """Create a PyLintItem for the File."""
      yield PyLintItem.from_parent(
          parent=self,
-         name='PYLINT'
+         name=self.name,
+         nodeid='{}::PYLINT'.format(self.nodeid)
      )
```

2020-10-14 03:41 UTC, yanqd0 commented
I'd like to improve. How to reproduct this layout?

```
setup.py
    # setup.py
    # setup.py
    # setup.py
    # PYLINT
```

2020-10-14 06:56 UTC, R-Broadley commented
> I'd like to improve. How to reproduct this layout?
> 
> ```
> setup.py.                 <- Test suite
>     # setup.py            <- Black style check results
>     # setup.py            <- isort check results
>     # setup.py            <- pydocstyle results
>     # PYLINT              <- pylint style check results
> ```

That is a simplified version of the output in an Allure html report (see here for generic example https://docs.qameta.io/allure/images/testcase.png). That is how it looks **with** your changes.
I've added comments above to show a bit more detail.

I think your approach is good, and naming the test PYTEST is sensible. I was just just pointing out that similar plugins have taken a different approach in setting name / nodeid. As far as I can tell this only affects certain reports and not the command line output.

Hope this pull request gets merged soon.

2020-10-14 10:18 UTC, yanqd0 commented
The display in CLI verbose mode is `self._nodeid` of a `pytest.Item`, that's a merge of `self.parent.nodeid` and `self.name`. For a  historical reason, most pytest linter plugins modify `self._nodeid` directly to handle the display.

I changed it in this patch. A `pytest.Item` should be named as `PLINT`, while its parent `pytest.File` named as `setup.py`. It may be better than the historical trick.

https://github.com/pytest-dev/pytest/blob/master/src/_pytest/nodes.py#L175-177

2020-10-14 11:58 UTC, R-Broadley commented
Yes I agree for the simple reason that It's confusing when multiple lint tests (items) have the same name.
I think other plugins should make similar changes as you have done.

Perhaps once this is merged I will raise issues to request they confirm to this (better) style.

2020-11-09 03:10 UTC, carsongee requested changes
I'm really sorry I didn't review this earlier. I oddly enough had an open review from a month ago, but apparently didn't submit it. Sorry about that, and thanks for the contribution.  I have to fix some additional degradation and push out a release today, so I may just patch these in with my suggested changes in another PR. Thanks again!

2020-11-09 03:10 UTC, carsongee commented on pytest_pylint/tests/test_pytest_pylint.py
> +# pylint: disable=not-callable
This disables the message at the module scope (whole file). It needs to move down into the function for the proper scoping

2020-11-09 03:10 UTC, carsongee commented on pytest_pylint/tests/test_pytest_pylint.py
> +    assert 'PYLINT' in result.stdout.str()
Same here, I'd prefer to keep the ::PYLINT, just remove the duplicated full path issue

2020-11-09 03:48 UTC, carsongee commented on pytest_pylint/plugin.py
> +            name='PYLINT',
Woops, nevermind, you're right here

2020-11-09 04:47 UTC, carsongee commented
I ended up putting this in with some additional fixes for the pytest master branch: https://github.com/carsongee/pytest-pylint/pull/145 Thanks again!

2020-11-09 04:47 UTC, closed without merging